class House {
  final int? id;
  final String name;
  final int floors;

  House({required this.id, required this.name, required this.floors});

  House.autoGenerated({required this.name, required this.floors})
      : id = null;

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'floors': floors,
    };
  }
}